name: Manual Trigger Example

on:
  workflow_dispatch:

jobs:
  run-manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Set output variable
        id: step1
        run: echo "current_time=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

      - name: Use output variable
        run: echo "The current time is ${{ steps.step1.outputs.current_time }}"
