name: Manual Trigger Example

on:
  workflow_dispatch:

jobs:
  run-manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a shell command
        run: echo "Current time: $(date '+%Y-%m-%d %H:%M:%S')"
